#!/bin/bash

make

if [[ -n $1 ]]; then
    [[ $1 != all ]] && pat=$1
    tests=$(find tests | grep "$pat")
    echo $tests $pat
    for test in $tests; do
        echo "==== Running on $test ===="
        build/myscript "$test"
    done
else
    echo "==== Running on stdin ===="
    build/myscript
fi
